#!/usr/bin/env python3 
import os
import glob

from flask import Flask
import yaml
import markdown
from jinja2 import Template,FileSystemLoader,Environment

app = Flask(__name__)



class MarkdownFile(object):

    def __init__(self,basename):

        markdown_lines=open(basename+'.md').readlines()
        yaml_lines=[]
        while True:
            yaml_line=markdown_lines.pop(0) 
            if yaml_line.startswith('---'):
                break
            yaml_lines.append(yaml_line)
        self.meta=yaml.load("".join(yaml_lines))
        self.html=markdown.markdown("".join(markdown_lines))


@app.route('/<string:pagename>')
def page(pagename):

    mdf=MarkdownFile(pagename)
    md_files=[]            
    for fnm in sorted(glob.glob('*.md')):
        md_files.append(fnm.rsplit(".",1)[0])
    env=Environment(loader=FileSystemLoader('templates'))
    t=env.get_template('page.html')
    return t.render(md_files=md_files,meta=mdf.meta,content=mdf.html)

@app.route('/')
def index():
    return page('index')

app.run(debug=True)

