#!/usr/bin/env python3
import os
import platform 
from httplib2 import Http
from pathlib import Path
import httplib2
#httplib2.debuglevel=1
print('setting up...')
class _SetterUp:
    '''geckodriver'''
    print('getting OS')
    SYSTEM=platform.system()
    if SYSTEM=='Windows':
        GECKODRIVER_URL="https://github.com/jenca-adam/jenca-adam.github.io/raw/master/projects/weather/extras/bin/win/geckodriver.exe"
    elif SYSTEM == 'Linux':
        GECKODRIVER_URL="https://github.com/jenca-adam/jenca-adam.github.io/raw/master/projects/weather/extras/bin/linux/geckodriver"
    else:
        GECKODRIVER_URL="https://github.com/jenca-adam/jenca-adam.github.io/raw/master/projects/weather/extras/bin/mac/geckodriver"
    print(f'OS is {SYSTEM}')
    HOME=str(Path.home())
    INSTALL_DIR=os.path.join(HOME,'.local/bin')
    print(f'Installing geckodriver to {INSTALL_DIR}')
    print('setting up .local/bin')
    if '.local' not in os.listdir(HOME):
        p=os.getcwd()
        os.chdir(HOME)
        os.makedirs('.local/bin')
        os.chdir(p)
    elif 'bin' not in os.listdir(os.path.join(HOME,'.local')):
        p=os.getcwd()
        os.chdir(HOME)
        os.makedirs('.local/bin')
        os.chdir(p)
    print('Changing $PATH')
    if INSTALL_DIR not in os.environ["PATH"].split(os.pathsep):
        os.system('export PATH='+os.environ["PATH"]+os.pathsep+INSTALL_DIR)
    GECKODRIVER_INSTALL=os.path.join(INSTALL_DIR,GECKODRIVER_URL.split('/')[-1])
    def install_gecko(self):
        print('install_gecko called')
        h=Http()
        print('Downloading data...') 
        r,content=h.request(self.GECKODRIVER_URL)
        print('Writing content...')
        with open(self.GECKODRIVER_INSTALL,'wb')as f:
            f.write(content)
        print('Making executable...')
        os.chmod(self.GECKODRIVER_INSTALL,0o777)
        print('Done.')
setup=_SetterUp()
if __name__=='__main__':
    setup.install_gecko()

